
name : "Deploy to Azure Kubernetes Service (AKS)"

on: 
  workflow_call:
    inputs:
      resource-group:
        required: true
        type: string        
      cluster-name:
        required: true
        type: string        
      namespace:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      client-id:
        required: true
      tenant-id:
        required: true
      subscription-id:      
        required: true


env:
  AZ_RESOURCE_GROUP: "tgrall-demo"
  AZ_CLUSTER_NAME: "tug-kube"
  NAMESPACE_DEV: "development"
  NAMESPACE_STAGING: "staging"
  NAMESPACE_PROD: "production"

permissions:
  id-token: write
  contents: read

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{inputs.environment}}   
      url: ${{steps.kube-deploy.outputs.service-url}}    
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.client-id }}
          tenant-id: ${{ secrets.tenant-id }}
          subscription-id: ${{ secrets.subscription-id }}
  
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get AKS Credentials
      id: getContext
      run: |
        az aks get-credentials --resource-group ${{ inputs.resource-group }} --name ${{ inputs.cluster-name }} --file $GITHUB_WORKSPACE/kubeconfig
        echo "KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig" >> $GITHUB_ENV      


    - name: "🌩️ - Deploy to ${{inputs.namespace}}"
      id: kube-deploy
      run: |
        kubectl create namespace ${{inputs.namespace}} --dry-run=client -o json | kubectl apply -f -                  
        kubectl apply -f ./deployment.yml --namespace=${{ inputs.namespace }}
        kubectl apply -f ./service.yml --namespace=${{ inputs.namespace }}
        echo "🕚  - Wait 20s for service deployment"
        sleep 20s
        IP_SERVICE=$(kubectl get services -n ${{ inputs.namespace }}  -o json | jq -r '.items[] | select(.metadata.name == "tug-sample-app") | .status.loadBalancer?|.ingress[]?|.ip')
        echo "IP_SERVICE=$IP_SERVICE" >> $GITHUB_ENV
        echo "🏁 - Service ${{ github.repository }} update in ${{inputs.namespace}} : http://$IP_SERVICE:8080 "
        echo "::set-output name=service-url::http://$IP_SERVICE:8080"     